"use client";

import { useActionState } from "react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

import { addBusinessPartyAddress, addBusinessPartyContact, createBusinessPartyCategory, initialMasterDataActionState, upsertBusinessParty } from "../commands";

function ActionMessage({ message, status }: { message?: string; status: "idle" | "success" | "error" }) {
  return message ? <p className={status === "error" ? "text-sm text-destructive sm:col-span-2" : "text-sm text-muted-foreground sm:col-span-2"}>{message}</p> : null;
}

export function BusinessPartyCategoryForm({ organisationId }: { organisationId: string }) {
  const [state, action, pending] = useActionState(createBusinessPartyCategory, initialMasterDataActionState);
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><input name="organisationId" type="hidden" value={organisationId} /><label className="grid gap-2"><Label htmlFor="categoryName">Category name</Label><Input id="categoryName" name="name" required /></label><label className="grid gap-2"><Label htmlFor="categoryType">Party type</Label><select className="h-10 rounded-md border bg-background px-3 text-sm" id="categoryType" name="partyType"><option value="customer">Customer</option><option value="supplier">Supplier</option><option value="both">Both</option></select></label><div className="sm:col-span-2"><Button disabled={pending} type="submit">{pending ? "Creating..." : "Create category"}</Button></div><ActionMessage message={state.message} status={state.status} /></form>;
}

export function BusinessPartyForm({ organisationId }: { organisationId: string }) {
  const [state, action, pending] = useActionState(upsertBusinessParty, initialMasterDataActionState);
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><input name="organisationId" type="hidden" value={organisationId} /><label className="grid gap-2"><Label htmlFor="partyDisplayName">Display name</Label><Input id="partyDisplayName" name="displayName" required /></label><label className="grid gap-2"><Label htmlFor="partyType">Party type</Label><select className="h-10 rounded-md border bg-background px-3 text-sm" id="partyType" name="partyType"><option value="customer">Customer</option><option value="supplier">Supplier</option><option value="both">Customer and supplier</option></select></label><label className="grid gap-2"><Label htmlFor="partyCode">External code</Label><Input id="partyCode" name="externalCode" /></label><label className="grid gap-2"><Label htmlFor="partyCategory">Category ID</Label><Input id="partyCategory" name="categoryId" /></label><label className="grid gap-2"><Label htmlFor="partyLegalName">Legal name</Label><Input id="partyLegalName" name="legalName" /></label><label className="grid gap-2"><Label htmlFor="partyTin">TIN</Label><Input id="partyTin" name="taxIdentificationNumber" /></label><label className="grid gap-2"><Label htmlFor="partyEmail">Email</Label><Input id="partyEmail" name="email" type="email" /></label><label className="grid gap-2"><Label htmlFor="partyPhone">Phone</Label><Input id="partyPhone" name="phone" /></label><label className="grid gap-2"><Label htmlFor="partyActive">Status</Label><select className="h-10 rounded-md border bg-background px-3 text-sm" id="partyActive" name="isActive"><option value="true">Active</option><option value="false">Inactive</option></select></label><div className="self-end"><Button disabled={pending} type="submit">{pending ? "Saving..." : "Save party"}</Button></div><ActionMessage message={state.message} status={state.status} /></form>;
}

export function BusinessPartyContactForm({ organisationId }: { organisationId: string }) {
  const [state, action, pending] = useActionState(addBusinessPartyContact, initialMasterDataActionState);
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><input name="organisationId" type="hidden" value={organisationId} /><label className="grid gap-2 sm:col-span-2"><Label htmlFor="contactPartyId">Party ID</Label><Input id="contactPartyId" name="partyId" required /></label><label className="grid gap-2"><Label htmlFor="contactName">Full name</Label><Input id="contactName" name="fullName" required /></label><label className="grid gap-2"><Label htmlFor="contactTitle">Job title</Label><Input id="contactTitle" name="jobTitle" /></label><label className="grid gap-2"><Label htmlFor="contactEmail">Email</Label><Input id="contactEmail" name="email" type="email" /></label><label className="grid gap-2"><Label htmlFor="contactPhone">Phone</Label><Input id="contactPhone" name="phone" /></label><label className="grid gap-2"><Label htmlFor="contactPrimary">Primary contact</Label><select className="h-10 rounded-md border bg-background px-3 text-sm" id="contactPrimary" name="isPrimary"><option value="false">No</option><option value="true">Yes</option></select></label><div className="self-end"><Button disabled={pending} type="submit">{pending ? "Adding..." : "Add contact"}</Button></div><ActionMessage message={state.message} status={state.status} /></form>;
}

export function BusinessPartyAddressForm({ organisationId }: { organisationId: string }) {
  const [state, action, pending] = useActionState(addBusinessPartyAddress, initialMasterDataActionState);
  return <form action={action} className="grid gap-3 sm:grid-cols-2"><input name="organisationId" type="hidden" value={organisationId} /><label className="grid gap-2 sm:col-span-2"><Label htmlFor="addressPartyId">Party ID</Label><Input id="addressPartyId" name="partyId" required /></label><label className="grid gap-2"><Label htmlFor="addressLabel">Label</Label><Input id="addressLabel" name="label" required /></label><label className="grid gap-2"><Label htmlFor="addressType">Address type</Label><select className="h-10 rounded-md border bg-background px-3 text-sm" id="addressType" name="addressType"><option value="physical">Physical</option><option value="billing">Billing</option><option value="delivery">Delivery</option><option value="postal">Postal</option></select></label><label className="grid gap-2 sm:col-span-2"><Label htmlFor="addressLine1">Address line</Label><Input id="addressLine1" name="line1" required /></label><label className="grid gap-2"><Label htmlFor="addressLine2">Address line 2</Label><Input id="addressLine2" name="line2" /></label><label className="grid gap-2"><Label htmlFor="addressCity">City</Label><Input id="addressCity" name="city" /></label><label className="grid gap-2"><Label htmlFor="addressRegion">Region</Label><Input id="addressRegion" name="region" /></label><label className="grid gap-2"><Label htmlFor="addressPostal">Postal code</Label><Input id="addressPostal" name="postalCode" /></label><label className="grid gap-2"><Label htmlFor="addressCountry">Country code</Label><Input defaultValue="TZ" id="addressCountry" maxLength={2} name="countryCode" required /></label><label className="grid gap-2"><Label htmlFor="addressPrimary">Primary address</Label><select className="h-10 rounded-md border bg-background px-3 text-sm" id="addressPrimary" name="isPrimary"><option value="false">No</option><option value="true">Yes</option></select></label><div className="self-end"><Button disabled={pending} type="submit">{pending ? "Adding..." : "Add address"}</Button></div><ActionMessage message={state.message} status={state.status} /></form>;
}
